name: Node.js CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm run test:unit
      env:
        NODE_ENV: test
        JWT_SECRET_KEY: test-secret-key
        JWT_REFRESH_KEY: test-refresh-key
        
    - name: Run integration tests
      run: npm run test:integration
      env:
        NODE_ENV: test
        JWT_SECRET_KEY: test-secret-key
        JWT_REFRESH_KEY: test-refresh-key
        
    - name: Generate coverage report
      run: npm run test:coverage
      env:
        NODE_ENV: test
        JWT_SECRET_KEY: test-secret-key
        JWT_REFRESH_KEY: test-refresh-key
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        fail_ci_if_error: false
